2021-09-18 17:25:58,303 INFO: Microblog startup [in /Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/__init__.py:57]
2021-09-18 17:26:05,654 INFO: Microblog startup [in /Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/__init__.py:57]
2021-09-18 18:28:23,212 INFO: Microblog startup [in /Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/__init__.py:57]
2021-09-18 18:29:46,057 INFO: Microblog startup [in /Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/__init__.py:57]
2021-09-18 18:29:51,807 ERROR: Exception on /edit_profile [GET] [in /Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/routes.py", line 106, in edit_profile
    return render_template('edit_profile.html', title = "Edit Profile", form = form)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/templates/edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock%}
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/templates/edit_profile.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask_wtf/form.py", line 134, in hidden_tag
    '\n'.join(str(f) for f in hidden_fields(fields or self))
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask_wtf/form.py", line 134, in <genexpr>
    '\n'.join(str(f) for f in hidden_fields(fields or self))
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask_wtf/form.py", line 124, in hidden_fields
    for f in fields:
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/wtforms/form.py", line 56, in __iter__
    return iter(itervalues(self._fields))
AttributeError: 'EditProfileForm' object has no attribute '_fields'
2021-09-18 18:31:46,609 INFO: Microblog startup [in /Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/__init__.py:57]
2021-09-18 18:33:24,410 INFO: Microblog startup [in /Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/__init__.py:57]
2021-09-18 18:33:37,174 INFO: Microblog startup [in /Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/__init__.py:57]
2021-09-18 18:33:40,271 ERROR: Exception on /edit_profile [GET] [in /Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py:1454]
Traceback (most recent call last):
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/routes.py", line 106, in edit_profile
    return render_template('edit_profile.html', title = "Edit Profile", form = form)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
    return _render(
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask/templating.py", line 128, in _render
    rv = template.render(context)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/templates/edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock%}
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/myapp/templates/edit_profile.html", line 6, in block 'content'
    {{ form.hidden_tag() }}
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask_wtf/form.py", line 134, in hidden_tag
    '\n'.join(str(f) for f in hidden_fields(fields or self))
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask_wtf/form.py", line 134, in <genexpr>
    '\n'.join(str(f) for f in hidden_fields(fields or self))
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/flask_wtf/form.py", line 124, in hidden_fields
    for f in fields:
  File "/Users/aaronwright/Documents/Tech/DataEngineer/Microblog/venv/lib/python3.9/site-packages/wtforms/form.py", line 56, in __iter__
    return iter(itervalues(self._fields))
AttributeError: 'EditProfileForm' object has no attribute '_fields'
